### ISSUE TITLE
no module named ftmstore

### ISSUE THREAD

**Issue by luisDiazStgo1994** [alephdata/opensanctions#67] opened 2020-11-17 17:12 UTC
when i run: sudo docker-compose up
i get the following error for each list:
  **ModuleNotFoundError: No module named 'ftmstore'**

Traceback is the following:
 **Traceback (most recent call last):
worker_1    |   File "/memorious/memorious/logic/context.py", line 77, in execute
worker_1    |     return self.stage.method(self, data)
worker_1    |   File "/memorious/memorious/logic/stage.py", line 28, in method
worker_1    |     module = import_module(package)
worker_1    |   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
worker_1    |     return _bootstrap._gcd_import(name[level:], package, level)
worker_1    |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
worker_1    |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
worker_1    |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
worker_1    |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
worker_1    |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
worker_1    |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
worker_1    |   File "/opensanctions/opensanctions/crawlers/au_dfat_sanctions.py", line 8, in <module>
worker_1    |     from ftmstore.memorious import EntityEmitter
worker_1    | ModuleNotFoundError: No module named 'ftmstore'**

**Comment by ChrisjanWust** [comment] 2020-12-14 12:17
It seems the issue isn't as simple as installing ftmstore (`followthemoney-store`) because of dependency conflicts.

From commit bfa4120aafb72bfe0786ca4ee765dc5d8229c29e, I've been able to get the project to run by pip installing the following module versions after doing a completed docker build:
`followthemoney==1.3.1`
`banal==1.0.1`

I have not yet been able to avoid dependency conflicts on the latest commit.

Full `pip freeze` output:
```
alembic==1.2.1
alephclient==2.2.2
asn1crypto==0.24.0
Babel==2.7.0
banal==1.0.1
boto3==1.9.253
botocore==1.12.253
cachetools==3.1.1
certifi==2019.9.11
cffi==1.11.5
chardet==3.0.4
Click==7.0
countrynames==1.6.0
cryptography==2.6.1
dataset==1.1.2
dateparser==0.7.2
decorator==4.4.1
docutils==0.15.2
et-xmlfile==1.0.1
fakeredis==1.0.3
Flask==1.1.1
followthemoney==1.31.1
followthemoney-store==2.2.3
google-api-core==1.14.3
google-auth==1.6.3
google-cloud-core==1.0.3
google-cloud-storage==1.20.0
google-resumable-media==0.4.1
googleapis-common-protos==1.6.0
gunicorn==19.7.1
idna==2.8
isodate==0.6.0
itsdangerous==1.1.0
jdcal==1.4.1
Jinja2==2.10.3
jmespath==0.9.4
languagecodes==1.0.5
lxml==4.3.4
Mako==1.1.0
MarkupSafe==1.1.1
# Editable install with no version control (memorious==1.2.9)
-e /memorious
networkx==2.4
normality==2.0.0
olefile==0.46
openpyxl==3.0.5
# Editable install with no version control (opensanctions==2.0)
-e /opensanctions
ordered-set==4.0.2
pantomime==0.3.3
phonenumbers==8.10.22
Pillow==6.0.0
protobuf==3.10.0
psycopg2==2.7.7
psycopg2-binary==2.8.4
pyasn1==0.4.7
pyasn1-modules==0.2.7
pycparser==2.19
PyICU==2.3.1
pyOpenSSL==19.0.0
pyparsing==2.4.2
python-dateutil==2.8.0
python-editor==1.0.4
python-Levenshtein==0.12.0
python-stdnum==1.12
pytz==2019.3
PyYAML==5.1.2
rdflib==4.2.2
redis==3.2.1
regex==2019.8.19
requests==2.22.0
requests-ftp==0.3.1
requests-toolbelt==0.9.1
rsa==4.0
s3transfer==0.2.1
servicelayer==1.8.4
six==1.12.0
sortedcontainers==2.1.0
SQLAlchemy==1.3.10
stringcase==1.2.0
tabulate==0.8.5
tesserocr==2.4.1
text-unidecode==1.3
tzlocal==2.0.0
urllib3==1.25.6
urlnormalizer==1.2.5
Werkzeug==0.16.0
xlrd==2.0.1
```

**Comment by ChrisjanWust** [comment] 2020-12-14 12:24
Nevermind, more module tinkering will be needed. The function `aleph_emit` is still not found.

**Comment by ChrisjanWust** [comment] 2020-12-14 12:45
The unknown `aleph_emit` method looks like unrelated, so I've made a new issue here: https://github.com/alephdata/opensanctions/issues/70

**Comment by sunu** [comment] 2020-12-14 15:15
Could you rebuild the docker images with `docker-compose build --no-cache`? From the `pip freeze` output I notice that you're running some very old version of `memorious`, `servicelayer`, `followthemoney`.

**Comment by ChrisjanWust** [comment] 2021-01-12 10:08
That did solve the problem :+1:

**Comment by sunu** [comment] 2021-01-13 06:02
Thanks for the confirmation. Closing the issue now

**Closed by sunu** 2021-01-13 06:02 UTC
